### ISSUE TITLE
minify executables

### ISSUE THREAD

**Issue by tasshi-me** [kintone/cli-kintone#103]
## Why

The compiled executable of cli-kintone is about 60MB.
I think that's because we don't minify the source code and the test code is included.

## What

- [ ] minify the `dist` directory before compiling to an executable file.
- [ ] exclude test codes from the build target.

**Comment by mshrtsr** [comment]
https://github.com/vitejs/vite
https://zenn.dev/manalink_dev/articles/vite-bundle-analyzer

**Comment by mshrtsr** [comment]
< 10MB is good, but I don't know whether we can realize it.
We use vercel/pkg to generate executables, and it bundles the Node.js binary to executables.
We cannot reduce the size of the Node.js binary.
