### ISSUE TITLE
【cli-kintone】Providing subcommand for command completion

### ISSUE THREAD

**Issue by hung-cybo** [kintone/cli-kintone#154]
## User Story

```
As a cli-kintone user, 
I want to support the autocomplete feature, 
so that I can reduce the time spent searching for command option names. 
  ```
searching for command option names: visiting cli-kintone's GitHub or devnet.

## Background
After finishing the investigation https://github.com/kintone/dx-internal/issues/599 , the next action is to provide a subcommand to support command completion.

## Acceptance Criteria
A subcommand to support command completion is provided.

**Comment by mshrtsr** [comment]
In this PBI, is the document necessary?

Yes, please.
Please write how to configure completion on README.md.
